language: ruby
before_install:
- gem install image_optim_pack
script:
- git config --global user.name 'travis-deploy'
- git config --global user.email 'travis-deploy@abwesend.com'
- git remote set-url origin https://beanieboi:${GH_TOKEN}@github.com/beanieboi/abwesend.com.git
- ALLOW_DIRTY=1 bundle exec rake publish
branches:
  only:
  - master
env:
  global:
  - secure: tYPFg8rKfW57N6UyfPEaz8zTIIREAcMNWH76F9zcu17fzHlYzX61ZdMSdpiB3ONBCcsE4L6GcACylzSuplQFO+6nFTwMfsxUstalAvt87XzrSGADFeN8TgQx4ZRnhYtI2MBvZQGZ8UsTzWA3y+TIM0oaRhumvT56iEPBjP6Rw+A=
